//
//  SettingsView.swift
//  GTS
//
//  Created by Tristan Chay on 22/11/23.
//

import SwiftUI

struct SettingsView: View {
    @State var toggle_Privacy = false
    
    var body: some View {
        VStack {
            VStack {
                Image(systemName: "photo")
                Text("Bio")
                Text("Count: ")
            }
            List {
                Button {
                    toggle_Privacy.toggle()
                } label: {
                    Text("Privacy Policy")
                }
            }
        }
        .sheet(isPresented: $toggle_Privacy) {
            ScrollView {
                VStack {
                    ForEach((1...4), id: \.self) {
                        Spacer()
                            .frame(height: 300 * CGFloat($0))
                        Text("""
                             Privacy Policy
                             Last updated: August 12, 1586
                             This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
                             We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. We also send all your personal data to 3rd parties in countries such as Russia and China
                             Interpretation and Definitions
                             Interpretation
                             The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
                             Definitions
                             For the purposes of this Privacy Policy:
                             account means a unique account created for You to access our Service or parts of our Service.
                             affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.
                             application refers to GTS, the software program provided by the Company.
                             company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to GTSm, SST Inc. HQ, School of Science and Technology, Singapore, Block C, Level 3, 1 Technology Drive, Singapore 138572.
                             country refers to: Singapore
                             device means any device that can access the Service such as a computer, a cellphone or a digital tablet.
                             personal data is any information that relates to an identified or identifiable individual.
                             service refers to the Application.
                             service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.
                             usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
                             you means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
                             Google Cloud API
                             Google API Services, including Google Sign-In, are part of an authentication and authorization framework that gives Us the ability to connect directly with Google users when We would like to request access to Google user data. We also sell them your data
                             Collecting and Using Your Personal Data
                             Types of Data Collected
                             EVERYTHING
                             WE COLLECT YOUR SOUL
                             WE COLLECT YOUR DREAMS

                             While using Our Service, We may ask You to provide Us with certain personally identifiable information that will be used only for the Google Cloud API. Personally identifiable information may include, but is not limited to:
                             Login Token
                             User Preference Information
                             Email address
                             Google Account
                             Google Classroom Data
                             Usage Data is collected automatically when using the Service.
                             We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.
                             Use of Your Personal Data
                             The Company may use Personal Data for the following purposes:
                             To provide and maintain our Service, including to monitor the usage of our Service.
                             To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.
                             For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.
                             To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.
                             To provide You with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.
                             To manage Your requests: To attend and manage Your requests to Us.
                             For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.
                             We may share Your personal information in the following situations:
                             With Service Providers: We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.
                             With Affiliates: We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.
                             With other users: when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.
                             With Your consent: We may disclose Your personal information for any other purpose with Your consent.
                             Storage of Your Personal Data
                             The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
                             The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.
                             Our Access to Your Personal Data
                             EVERYTHING AND I MEANT IT
                             Delete Your Personal Data
                             You do not have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.
                             Law enforcement
                             Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
                             Other legal requirements
                             The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:
                             Comply with a legal obligation
                             Protect and defend the rights or property of the Company
                             Prevent or investigate possible wrongdoing in connection with the Service
                             Protect the personal safety of Users of the Service or the public
                             Protect against legal liability
                             Security of Your Personal Data
                             The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
                             Children's Privacy
                             No touching of children
                             Changes to this Privacy Policy
                             We may update Our Privacy Policy from time to time. We will never notify You of any changes by posting the new Privacy Policy on this page.
                             Contact Us
                             If you have any questions about this Privacy Policy, You can contact us: at jeffreyepstein@gmail.com
                             """)
                        Spacer()
                            .frame(height: 300 / CGFloat($0))
                    }
                    HStack {
                        Button {
                            toggle_Privacy = false
                        } label: {
                            Text("i don't understand")
                        }
                        Button {
                            toggle_Privacy.toggle()
                        } label: {
                            Text("this amazing text")
                        }
                    }
                }
            }
        }
    }
}

#Preview {
    SettingsView()
}
